### PR TITLE
New bootstrap types

### PR DESCRIPTION
**Pull request by adam-yorwerth**

### CODE REVIEW

**Comment by sebastianlavender** [comment]
What's the rational behind having the delay hardcoded as a property value rather than an optional parameter in the bootstrap type? Only curious as it would mean redeploying the provider if we wanted to change this time.

**Comment by adam-yorwerth** [comment]
> What's the rational behind having the delay hardcoded as a property value rather than an optional parameter in the bootstrap type? Only curious as it would mean redeploying the provider if we wanted to change this time.

Trying to make it compatible with existing version of the pipe/provider lead to this - any ideas to make it dynamic and ensure this would be great (optional header maybe?)

**Comment by sebastianlavender** [comment]
> > What's the rational behind having the delay hardcoded as a property value rather than an optional parameter in the bootstrap type? Only curious as it would mean redeploying the provider if we wanted to change this time.
> 
> Trying to make it compatible with existing version of the pipe/provider lead to this - any ideas to make it dynamic and ensure this would be great (optional header maybe?)

I think the idea of an optional header would be good and give us more flexibility changing the time

**Review by LorenzoCianciaruso — APPROVED** [review]
LGTM

**Pull request merged**
