### PR TITLE
Compaction in cloud runs every hour

### PR DESCRIPTION
**Pull request by sebastianlavender**
- compaction runs on the 14th minute every hour

### CODE REVIEW

**Review by adam-yorwerth — COMMENTED** [review]
Can we edit the test for this too?

**Comment by sebastianlavender** [comment]
> Can we edit the test for this too?

Which test are you referring to?

**Comment by adam-yorwerth** [comment]
> > Can we edit the test for this too?
> 
> Which test are you referring to?

CompactionTaskSpec

**Comment by sebastianlavender** [comment]
> > > Can we edit the test for this too?
> > 
> > 
> > Which test are you referring to?
> 
> CompactionTaskSpec

Added into test with the cron expression used in prod

**Review by adam-yorwerth — APPROVED** [review]

**Pull request merged**
